### ISSUE TITLE
Comptabilisation routage en mode forcé 

### ISSUE THREAD

**Issue by Stabu1** [Jetblack31/MaxPV#13]
Bonjour 
Tout d’abord un grand bravo pour le travail formidable. Depuis la v3.5 la comptabilisation de la puissance routé inclue    la puissance consommée en mode forcé ce qui n’est pas logique. En version 3.35 ce n’était pas le cas, en mode forcé la nuit on ne peut pas considérer et comptabiliser un routage. Merci.

**Comment by Jetblack31** [comment]
Bonsoir,

Merci pour le retour !
L'accumulation de l'énergie routée en mode FORCE ou BOOST était une demande de certains utilisateurs pour que le compteur d'énergie routée devienne un compteur d'énergie de production d'eau chaude.
D'où la modification en version 3.5.
Si vous voulez revenir au comportement initial, modifiez la ligne 690 du programme EcoPV en : 

if ( triacMode == 9) routedEnergy += Prouted;

et uploadez le nano avec ce programme modifié.

Jetblack

**Comment by Stabu1** [comment]
Merci pour la réponse et réactivité !
Je ferme l'issue.

**Comment by Jetblack31** [comment]
Pour utiliser le #define du code, il serait plus "propre" d'utiliser 

`if ( triacMode == AUTOM ) routedEnergy += Prouted;
`
